// Code generated by internal/genhelp; DO NOT EDIT.

//go:build urfave_cli_no_template

package cli

import "strings"

// renderCommandHelpTemplate renders CommandHelpTemplate template.
func renderCommandHelpTemplate(h *helpRenderer, dot *Command) {
	_ = dot
	h.WriteString("NAME:\n   ")
	render_helpNameTemplate_Command(h, dot)
	h.WriteString("\n\nUSAGE:\n   ")
	render_usageTemplate_Command(h, dot)
	if dot.Category != "" {
		h.WriteString("\n\nCATEGORY:\n   ")
		h.WriteString(dot.Category)
	}
	if dot.Description != "" {
		h.WriteString("\n\nDESCRIPTION:\n   ")
		render_descriptionTemplate_Command(h, dot)
	}
	if len(dot.VisibleFlagCategories()) != 0 {
		h.WriteString("\n\nOPTIONS:")
		render_visibleFlagCategoryTemplate_Command(h, dot)
	} else {
		if len(dot.VisibleFlags()) != 0 {
			h.WriteString("\n\nOPTIONS:")
			render_visibleFlagTemplate_Command(h, dot)
		}
	}
	if len(dot.VisiblePersistentFlags()) != 0 {
		h.WriteString("\n\nGLOBAL OPTIONS:")
		render_visiblePersistentFlagTemplate_Command(h, dot)
	}
	h.WriteString("\n")
}

// renderFishCompletionTemplate renders FishCompletionTemplate template.
func renderFishCompletionTemplate(h *helpRenderer, dot *fishCommandCompletionTemplate) {
	_ = dot
	h.WriteString("# ")
	h.WriteString(dot.Command.Name)
	h.WriteString(" fish shell completion\n\nfunction __fish_")
	h.WriteString(dot.Command.Name)
	h.WriteString("_no_subcommand --description 'Test if there has been any subcommand yet'\n    for i in (commandline -opc)\n        if contains -- $i")
	for i1, e2 := range dot.AllCommands {
		_, _ = i1, e2
		h.WriteString(" ")
		h.WriteString(e2)
	}
	h.WriteString("\n            return 1\n        end\n    end\n    return 0\nend\n\n")
	for i3, e4 := range dot.Completions {
		_, _ = i3, e4
		h.WriteString(e4)
		h.WriteString("\n")
	}
}

// renderRootCommandHelpTemplate renders RootCommandHelpTemplate template.
func renderRootCommandHelpTemplate(h *helpRenderer, dot *Command) {
	_ = dot
	h.WriteString("NAME:\n   ")
	render_helpNameTemplate_Command(h, dot)
	h.WriteString("\n\nUSAGE:\n   ")
	if dot.UsageText != "" {
		h.WriteString(h.wrap(dot.UsageText, 3))
	} else {
		h.WriteString(dot.FullName())
		h.WriteString(" ")
		if len(dot.VisibleFlags()) != 0 {
			h.WriteString("[global options]")
		}
		if len(dot.VisibleCommands()) != 0 {
			h.WriteString(" [command [command options]]")
		}
		if dot.ArgsUsage != "" {
			h.WriteString(" ")
			h.WriteString(dot.ArgsUsage)
		} else {
			if len(dot.Arguments) != 0 {
				h.WriteString(" [arguments...]")
			}
		}
	}
	if dot.Version != "" {
		if !dot.HideVersion {
			h.WriteString("\n\nVERSION:\n   ")
			h.WriteString(dot.Version)
		}
	}
	if dot.Description != "" {
		h.WriteString("\n\nDESCRIPTION:\n   ")
		render_descriptionTemplate_Command(h, dot)
	}
	if len(dot.Authors) != 0 {
		h.WriteString("\n\nAUTHOR")
		render_authorsTemplate_Command(h, dot)
	}
	if len(dot.VisibleCommands()) != 0 {
		h.WriteString("\n\nCOMMANDS:")
		render_visibleCommandCategoryTemplate_Command(h, dot)
	}
	if len(dot.VisibleFlagCategories()) != 0 {
		h.WriteString("\n\nGLOBAL OPTIONS:")
		render_visibleFlagCategoryTemplate_Command(h, dot)
	} else {
		if len(dot.VisibleFlags()) != 0 {
			h.WriteString("\n\nGLOBAL OPTIONS:")
			render_visibleFlagTemplate_Command(h, dot)
		}
	}
	if dot.Copyright != "" {
		h.WriteString("\n\nCOPYRIGHT:\n   ")
		render_copyrightTemplate_Command(h, dot)
	}
	h.WriteString("\n")
}

// renderSubcommandHelpTemplate renders SubcommandHelpTemplate template.
func renderSubcommandHelpTemplate(h *helpRenderer, dot *Command) {
	_ = dot
	h.WriteString("NAME:\n   ")
	render_helpNameTemplate_Command(h, dot)
	h.WriteString("\n\nUSAGE:\n   ")
	if dot.UsageText != "" {
		h.WriteString(h.wrap(dot.UsageText, 3))
	} else {
		h.WriteString(dot.FullName())
		if len(dot.VisibleCommands()) != 0 {
			h.WriteString(" [command [command options]]")
		}
		if dot.ArgsUsage != "" {
			h.WriteString(" ")
			h.WriteString(dot.ArgsUsage)
		} else {
			if len(dot.Arguments) != 0 {
				h.WriteString(" [arguments...]")
			}
		}
	}
	if dot.Category != "" {
		h.WriteString("\n\nCATEGORY:\n   ")
		h.WriteString(dot.Category)
	}
	if dot.Description != "" {
		h.WriteString("\n\nDESCRIPTION:\n   ")
		render_descriptionTemplate_Command(h, dot)
	}
	if len(dot.VisibleCommands()) != 0 {
		h.WriteString("\n\nCOMMANDS:")
		render_visibleCommandTemplate_Command(h, dot)
	}
	if len(dot.VisibleFlagCategories()) != 0 {
		h.WriteString("\n\nOPTIONS:")
		render_visibleFlagCategoryTemplate_Command(h, dot)
	} else {
		if len(dot.VisibleFlags()) != 0 {
			h.WriteString("\n\nOPTIONS:")
			render_visibleFlagTemplate_Command(h, dot)
		}
	}
	if len(dot.VisiblePersistentFlags()) != 0 {
		h.WriteString("\n\nGLOBAL OPTIONS:")
		render_visiblePersistentFlagTemplate_Command(h, dot)
	}
	h.WriteString("\n")
}

// render_argsTemplate_Command renders argsTemplate template.
func render_argsTemplate_Command(h *helpRenderer, dot *Command) {
	_ = dot
	if len(dot.Arguments) != 0 {
		for i1, e2 := range dot.Arguments {
			_, _ = i1, e2
			h.WriteString(e2.Usage())
			h.WriteString(" ")
		}
	}
}

// render_authorsTemplate_Command renders authorsTemplate template.
func render_authorsTemplate_Command(h *helpRenderer, dot *Command) {
	_ = dot
	if w1 := len(dot.Authors); w1 != 0 {
		_ = w1
		if 1 != w1 {
			h.WriteString("S")
		}
	}
	h.WriteString(":\n   ")
	for i2, e3 := range dot.Authors {
		_, _ = i2, e3
		if i2 != 0 {
			h.WriteString("\n   ")
		}
		h.WriteString(printableValue(e3))
	}
}

// render_copyrightTemplate_Command renders copyrightTemplate template.
func render_copyrightTemplate_Command(h *helpRenderer, dot *Command) {
	_ = dot
	h.WriteString(h.wrap(dot.Copyright, 3))
}

// render_descriptionTemplate_Command renders descriptionTemplate template.
func render_descriptionTemplate_Command(h *helpRenderer, dot *Command) {
	_ = dot
	h.WriteString(h.wrap(dot.Description, 3))
}

// render_helpNameTemplate_Command renders helpNameTemplate template.
func render_helpNameTemplate_Command(h *helpRenderer, dot *Command) {
	_ = dot
	v1 := offset(dot.FullName(), 6)
	_ = v1
	h.WriteString(h.wrap(dot.FullName(), 3))
	if dot.Usage != "" {
		h.WriteString(" - ")
		h.WriteString(h.wrap(dot.Usage, v1))
	}
}

// render_usageTemplate_Command renders usageTemplate template.
func render_usageTemplate_Command(h *helpRenderer, dot *Command) {
	_ = dot
	if dot.UsageText != "" {
		h.WriteString(h.wrap(dot.UsageText, 3))
	} else {
		h.WriteString(dot.FullName())
		if len(dot.VisibleFlags()) != 0 {
			h.WriteString(" [options]")
		}
		if len(dot.VisibleCommands()) != 0 {
			h.WriteString(" [command [command options]]")
		}
		if dot.ArgsUsage != "" {
			h.WriteString(" ")
			h.WriteString(dot.ArgsUsage)
		} else {
			if len(dot.Arguments) != 0 {
				h.WriteString(" ")
				render_argsTemplate_Command(h, dot)
			}
		}
	}
}

// render_visibleCommandCategoryTemplate_Command renders visibleCommandCategoryTemplate template.
func render_visibleCommandCategoryTemplate_Command(h *helpRenderer, dot *Command) {
	_ = dot
	for i1, e2 := range dot.VisibleCategories() {
		_, _ = i1, e2
		if e2.Name() != "" {
			h.WriteString("\n\n   ")
			h.WriteString(e2.Name())
			h.WriteString(":")
			for i3, e4 := range e2.VisibleCommands() {
				_, _ = i3, e4
				h.WriteString("\n     ")
				h.WriteString(strings.Join(e4.Names(), ", "))
				h.WriteString("\t")
				h.WriteString(e4.Usage)
			}
		} else {
			render_visibleCommandTemplate_CommandCategory(h, e2)
		}
	}
}

// render_visibleCommandTemplate_Command renders visibleCommandTemplate template.
func render_visibleCommandTemplate_Command(h *helpRenderer, dot *Command) {
	_ = dot
	v1 := offsetCommands(dot.VisibleCommands(), 5)
	_ = v1
	for i2, e3 := range dot.VisibleCommands() {
		_, _ = i2, e3
		h.WriteString("\n   ")
		v4 := strings.Join(e3.Names(), ", ")
		_ = v4
		h.WriteString(v4)
		v5 := subtract(v1, (offset(v4, 3)))
		_ = v5
		h.WriteString(indent(v5, ""))
		h.WriteString(h.wrap(e3.Usage, v1))
	}
}

// render_visibleCommandTemplate_CommandCategory renders visibleCommandTemplate template.
func render_visibleCommandTemplate_CommandCategory(h *helpRenderer, dot CommandCategory) {
	_ = dot
	v1 := offsetCommands(dot.VisibleCommands(), 5)
	_ = v1
	for i2, e3 := range dot.VisibleCommands() {
		_, _ = i2, e3
		h.WriteString("\n   ")
		v4 := strings.Join(e3.Names(), ", ")
		_ = v4
		h.WriteString(v4)
		v5 := subtract(v1, (offset(v4, 3)))
		_ = v5
		h.WriteString(indent(v5, ""))
		h.WriteString(h.wrap(e3.Usage, v1))
	}
}

// render_visibleFlagCategoryTemplate_Command renders visibleFlagCategoryTemplate template.
func render_visibleFlagCategoryTemplate_Command(h *helpRenderer, dot *Command) {
	_ = dot
	for i1, e2 := range dot.VisibleFlagCategories() {
		_, _ = i1, e2
		h.WriteString("\n   ")
		if e2.Name() != "" {
			h.WriteString(e2.Name())
			h.WriteString("\n\n   ")
		}
		v3 := len(e2.Flags())
		_ = v3
		for i4, e5 := range e2.Flags() {
			_, _ = i4, e5
			if (subtract(v3, i4)) == 1 {
				h.WriteString(printableValue(e5))
				h.WriteString("\n")
			} else {
				h.WriteString(printableValue(e5))
				h.WriteString("\n   ")
			}
		}
	}
}

// render_visibleFlagTemplate_Command renders visibleFlagTemplate template.
func render_visibleFlagTemplate_Command(h *helpRenderer, dot *Command) {
	_ = dot
	for i1, e2 := range dot.VisibleFlags() {
		_, _ = i1, e2
		h.WriteString("\n   ")
		h.WriteString(h.wrap(e2.String(), 6))
	}
}

// render_visiblePersistentFlagTemplate_Command renders visiblePersistentFlagTemplate template.
func render_visiblePersistentFlagTemplate_Command(h *helpRenderer, dot *Command) {
	_ = dot
	for i1, e2 := range dot.VisiblePersistentFlags() {
		_, _ = i1, e2
		h.WriteString("\n   ")
		h.WriteString(h.wrap(e2.String(), 6))
	}
}
