#!/bin/bash

: ${PROG:=$(basename ${BASH_SOURCE})}

_cli_bash_autocomplete() {
    local cur opts base replylen

    cur="${COMP_WORDS[COMP_CWORD]}"

    if [ -n "${cur}" ] ; then
      COMPREPLY=( $(compgen -S / -d -- ${cur}) )
    else
      COMPREPLY=()
    fi

    replylen=${#COMPREPLY}
    opts=$( ${COMP_WORDS[@]:0:$COMP_CWORD} --generate-bash-completion )
    COMPREPLY=( "${COMPREPLY[@]}" $(compgen -W "${opts}" -- ${cur}) )

    if [ ${#COMPREPLY} -eq ${replylen} ] ; then
      compopt -o nospace
    fi

    return 0
}

complete -F _cli_bash_autocomplete $PROG
