// Command genhelp compiles the default help and fish completion templates
// (see template.go) into Go code, which is used when the package is built
// with urfave_cli_no_template tag.
//
// Templates are parsed using text/template/parse, and field and method
// references are resolved statically, using go/types information for the
// cli package. Only a subset of the template language used by the default
// templates is supported; anything else results in an error.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/build"
	"go/constant"
	"go/format"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"text/template/parse"
)

var outFile = flag.String("o", "help_notemplate_gen.go", "output file")

// entry points: template variable name -> dot type name.
var entries = []struct{ tmpl, dot string }{
	{"RootCommandHelpTemplate", "*Command"},
	{"CommandHelpTemplate", "*Command"},
	{"SubcommandHelpTemplate", "*Command"},
	{"FishCompletionTemplate", "*fishCommandCompletionTemplate"},
}

// funcs are the template functions (see DefaultPrintHelpCustom),
// mapped to Go code and result types.
var funcs = map[string]struct {
	code string
	res  types.Type
}{
	"join":           {"strings.Join", types.Typ[types.String]},
	"subtract":       {"subtract", types.Typ[types.Int]},
	"indent":         {"indent", types.Typ[types.String]},
	"nindent":        {"nindent", types.Typ[types.String]},
	"trim":           {"strings.TrimSpace", types.Typ[types.String]},
	"wrap":           {"h.wrap", types.Typ[types.String]},
	"offset":         {"offset", types.Typ[types.Int]},
	"offsetCommands": {"offsetCommands", types.Typ[types.Int]},
}

func main() {
	log.SetFlags(0)
	log.SetPrefix("genhelp: ")
	flag.Parse()
	if err := run(); err != nil {
		log.Fatal(err)
	}
}

func run() error {
	pkg, sources, err := loadPackage(".")
	if err != nil {
		return err
	}
	g := &generator{pkg: pkg, sources: sources, done: map[string]string{}}
	for _, e := range entries {
		typ, err := g.lookupType(e.dot)
		if err != nil {
			return err
		}
		if _, err := g.instantiate(e.tmpl, "render"+e.tmpl, typ); err != nil {
			return fmt.Errorf("%s: %w", e.tmpl, err)
		}
	}

	names := make([]string, 0, len(g.bodies))
	for name := range g.bodies {
		names = append(names, name)
	}
	sort.Strings(names)
	var body bytes.Buffer
	for _, name := range names {
		body.WriteString(g.bodies[name])
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by internal/genhelp; DO NOT EDIT.\n\n" +
		"//go:build urfave_cli_no_template\n\npackage cli\n\n")
	if bytes.Contains(body.Bytes(), []byte("strings.")) {
		out.WriteString("import \"strings\"\n\n")
	}
	out.Write(body.Bytes())

	src, err := format.Source(out.Bytes())
	if err != nil {
		return fmt.Errorf("formatting generated code: %w\n%s", err, out.Bytes())
	}
	return os.WriteFile(*outFile, src, 0o644)
}

// loadPackage type-checks the package in dir (without any build tags,
// so the generated file is not included), and returns it along with
// the values of all package-level string variables and constants.
func loadPackage(dir string) (*types.Package, map[string]string, error) {
	bp, err := build.Default.ImportDir(dir, 0)
	if err != nil {
		return nil, nil, err
	}
	fset := token.NewFileSet()
	var files []*ast.File
	for _, name := range bp.GoFiles {
		f, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, 0)
		if err != nil {
			return nil, nil, err
		}
		files = append(files, f)
	}
	conf := types.Config{Importer: importer.ForCompiler(fset, "source", nil)}
	info := &types.Info{Types: map[ast.Expr]types.TypeAndValue{}}
	pkg, err := conf.Check(bp.ImportPath, fset, files, info)
	if err != nil {
		return nil, nil, err
	}

	sources := map[string]string{}
	for _, f := range files {
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || (gd.Tok != token.VAR && gd.Tok != token.CONST) {
				continue
			}
			for _, spec := range gd.Specs {
				vs := spec.(*ast.ValueSpec)
				for i, name := range vs.Names {
					if i >= len(vs.Values) {
						continue
					}
					if tv := info.Types[vs.Values[i]]; tv.Value != nil && tv.Value.Kind() == constant.String {
						sources[name.Name] = constant.StringVal(tv.Value)
					}
				}
			}
		}
	}
	return pkg, sources, nil
}

type generator struct {
	pkg     *types.Package
	sources map[string]string // template sources, by name
	done    map[string]string // instantiated function names, by template name and dot type
	bodies  map[string]string // generated functions, by function name
}

func (g *generator) lookupType(name string) (types.Type, error) {
	ptr := strings.HasPrefix(name, "*")
	obj := g.pkg.Scope().Lookup(strings.TrimPrefix(name, "*"))
	if obj == nil {
		return nil, fmt.Errorf("type %s not found", name)
	}
	typ := obj.Type()
	if ptr {
		typ = types.NewPointer(typ)
	}
	return typ, nil
}

func (g *generator) typeString(t types.Type) string {
	return types.TypeString(t, types.RelativeTo(g.pkg))
}

// instantiate generates a function rendering the template tmpl for the
// dot of the type dot, and returns its name. If fn is empty, a name is
// generated.
func (g *generator) instantiate(tmpl, fn string, dot types.Type) (string, error) {
	key := tmpl + " " + g.typeString(dot)
	if name, ok := g.done[key]; ok {
		return name, nil
	}
	if fn == "" {
		// Use the type name (without package and pointer) as a suffix,
		// so that names are stable and templates can be instantiated
		// for different dot types.
		typ := g.typeString(dot)
		typ = typ[strings.LastIndexAny(typ, "*.]")+1:]
		fn = "render_" + tmpl + "_" + typ
	}
	g.done[key] = fn

	src, ok := g.sources[tmpl]
	if !ok {
		return "", fmt.Errorf("template %q not found", tmpl)
	}
	trees, err := parse.Parse(tmpl, src, "", "", builtinFuncs())
	if err != nil {
		return "", err
	}
	tree := trees[tmpl]
	if len(trees) != 1 || tree == nil {
		return "", fmt.Errorf("template %q: nested definitions are not supported", tmpl)
	}

	f := &funcGen{g: g, tree: tree, vars: []map[string]value{{"$": {"dot", dot}}}}
	f.printf("// %s renders %s template.\n", fn, tmpl)
	f.printf("func %s(h *helpRenderer, dot %s) {\n_ = dot\n", fn, g.typeString(dot))
	if err := f.list(tree.Root, value{"dot", dot}); err != nil {
		return "", fmt.Errorf("template %q: %w", tmpl, err)
	}
	f.printf("}\n\n")
	if g.bodies == nil {
		g.bodies = map[string]string{}
	}
	g.bodies[fn] = f.String()
	return fn, nil
}

func builtinFuncs() map[string]any {
	m := map[string]any{}
	for _, name := range []string{"len", "eq", "ne", "not"} {
		m[name] = true // parse only checks the name is defined
	}
	for name := range funcs {
		m[name] = true // parse only checks the name is defined
	}
	return m
}

// value is a Go expression with its type.
type value struct {
	code string
	typ  types.Type
}

type funcGen struct {
	bytes.Buffer
	g    *generator
	tree *parse.Tree
	vars []map[string]value // variable scopes
	n    int                // counter for generating unique names
}

func (f *funcGen) printf(format string, args ...any) {
	fmt.Fprintf(f, format, args...)
}

// loc returns the location of n in the template, for error messages.
func (f *funcGen) loc(n parse.Node) string {
	loc, _ := f.tree.ErrorContext(n)
	return loc
}

func (f *funcGen) newName(prefix string) string {
	f.n++
	return fmt.Sprintf("%s%d", prefix, f.n)
}

func (f *funcGen) push() { f.vars = append(f.vars, map[string]value{}) }
func (f *funcGen) pop()  { f.vars = f.vars[:len(f.vars)-1] }

func (f *funcGen) setVar(name string, v value) {
	f.vars[len(f.vars)-1][name] = v
}

func (f *funcGen) lookupVar(name string) (value, error) {
	for i := len(f.vars) - 1; i >= 0; i-- {
		if v, ok := f.vars[i][name]; ok {
			return v, nil
		}
	}
	return value{}, fmt.Errorf("undefined variable %s", name)
}

func (f *funcGen) list(l *parse.ListNode, dot value) error {
	if l == nil {
		return nil
	}
	for _, n := range l.Nodes {
		if err := f.node(n, dot); err != nil {
			return err
		}
	}
	return nil
}

func (f *funcGen) node(n parse.Node, dot value) error {
	switch n := n.(type) {
	case *parse.TextNode:
		if len(n.Text) > 0 {
			f.printf("h.WriteString(%s)\n", strconv.Quote(string(n.Text)))
		}
		return nil
	case *parse.ActionNode:
		return f.action(n.Pipe, dot)
	case *parse.IfNode:
		return f.ifNode(n, dot)
	case *parse.WithNode:
		return f.with(n, dot)
	case *parse.RangeNode:
		return f.rangeNode(n, dot)
	case *parse.TemplateNode:
		return f.template(n, dot)
	case *parse.CommentNode:
		return nil
	}
	return fmt.Errorf("%s: unsupported node %q", f.loc(n), n)
}

// action handles {{pipeline}} and {{$x := pipeline}}.
func (f *funcGen) action(p *parse.PipeNode, dot value) error {
	v, err := f.pipe(p, dot)
	if err != nil {
		return err
	}
	if len(p.Decl) == 0 {
		f.print(v)
		return nil
	}
	if len(p.Decl) != 1 || p.IsAssign {
		return fmt.Errorf("%s: unsupported variable declaration %q", f.loc(p), p)
	}
	name := f.newName("v")
	f.printf("%s := %s\n_ = %s\n", name, v.code, name)
	f.setVar(p.Decl[0].Ident[0], value{name, v.typ})
	return nil
}

func (f *funcGen) print(v value) {
	if b, ok := v.typ.Underlying().(*types.Basic); ok && b.Info()&types.IsString != 0 {
		f.printf("h.WriteString(%s)\n", v.code)
		return
	}
	f.printf("h.WriteString(printableValue(%s))\n", v.code)
}

func (f *funcGen) ifNode(n *parse.IfNode, dot value) error {
	if len(n.Pipe.Decl) != 0 {
		return fmt.Errorf("%s: variables in if are not supported", f.loc(n))
	}
	v, err := f.pipe(n.Pipe, dot)
	if err != nil {
		return err
	}
	f.printf("if %s {\n", truth(v))
	f.push()
	if err := f.list(n.List, dot); err != nil {
		return err
	}
	f.pop()
	if n.ElseList != nil {
		f.printf("} else {\n")
		f.push()
		if err := f.list(n.ElseList, dot); err != nil {
			return err
		}
		f.pop()
	}
	f.printf("}\n")
	return nil
}

func (f *funcGen) with(n *parse.WithNode, dot value) error {
	if n.ElseList != nil {
		return fmt.Errorf("%s: else in with is not supported", f.loc(n))
	}
	v, err := f.pipe(n.Pipe, dot)
	if err != nil {
		return err
	}
	name := f.newName("w")
	f.printf("if %s := %s; %s {\n_ = %s\n", name, v.code, truth(value{name, v.typ}), name)
	f.push()
	nv := value{name, v.typ}
	switch len(n.Pipe.Decl) {
	case 0:
	case 1:
		f.setVar(n.Pipe.Decl[0].Ident[0], nv)
	default:
		return fmt.Errorf("%s: unsupported variable declaration in with", f.loc(n))
	}
	if err := f.list(n.List, nv); err != nil {
		return err
	}
	f.pop()
	f.printf("}\n")
	return nil
}

func (f *funcGen) rangeNode(n *parse.RangeNode, dot value) error {
	if n.ElseList != nil {
		return fmt.Errorf("%s: else in range is not supported", f.loc(n))
	}
	v, err := f.pipe(n.Pipe, dot)
	if err != nil {
		return err
	}
	var elem types.Type
	switch t := v.typ.Underlying().(type) {
	case *types.Slice:
		elem = t.Elem()
	case *types.Array:
		elem = t.Elem()
	default:
		return fmt.Errorf("%s: can't range over %s", f.loc(n), f.g.typeString(v.typ))
	}
	idx, el := f.newName("i"), f.newName("e")
	f.printf("for %s, %s := range %s {\n_, _ = %s, %s\n", idx, el, v.code, idx, el)
	f.push()
	ev := value{el, elem}
	switch len(n.Pipe.Decl) {
	case 0:
	case 1:
		f.setVar(n.Pipe.Decl[0].Ident[0], ev)
	case 2:
		f.setVar(n.Pipe.Decl[0].Ident[0], value{idx, types.Typ[types.Int]})
		f.setVar(n.Pipe.Decl[1].Ident[0], ev)
	default:
		return fmt.Errorf("%s: unsupported variable declaration in range", f.loc(n))
	}
	if err := f.list(n.List, ev); err != nil {
		return err
	}
	f.pop()
	f.printf("}\n")
	return nil
}

func (f *funcGen) template(n *parse.TemplateNode, dot value) error {
	arg := dot
	if n.Pipe != nil {
		var err error
		if arg, err = f.pipe(n.Pipe, dot); err != nil {
			return err
		}
	}
	fn, err := f.g.instantiate(n.Name, "", arg.typ)
	if err != nil {
		return err
	}
	f.printf("%s(h, %s)\n", fn, arg.code)
	return nil
}

func (f *funcGen) pipe(p *parse.PipeNode, dot value) (value, error) {
	if len(p.Cmds) != 1 {
		return value{}, fmt.Errorf("%s: pipelines are not supported", f.loc(p))
	}
	return f.command(p.Cmds[0], dot)
}

func (f *funcGen) command(c *parse.CommandNode, dot value) (value, error) {
	if id, ok := c.Args[0].(*parse.IdentifierNode); ok {
		return f.call(id, c.Args[1:], dot)
	}
	if len(c.Args) != 1 {
		return value{}, fmt.Errorf("%s: arguments are only supported for functions", f.loc(c))
	}
	return f.arg(c.Args[0], dot)
}

func (f *funcGen) call(id *parse.IdentifierNode, args []parse.Node, dot value) (value, error) {
	vals := make([]value, len(args))
	codes := make([]string, len(args))
	for i, a := range args {
		v, err := f.arg(a, dot)
		if err != nil {
			return value{}, err
		}
		vals[i], codes[i] = v, v.code
	}
	boolean := types.Typ[types.Bool]
	switch id.Ident {
	case "len":
		if len(vals) != 1 {
			return value{}, errors.New("len: wrong number of arguments")
		}
		return value{"len(" + codes[0] + ")", types.Typ[types.Int]}, nil
	case "eq", "ne":
		if len(vals) != 2 {
			return value{}, fmt.Errorf("%s: only two arguments are supported", id.Ident)
		}
		op := map[string]string{"eq": "==", "ne": "!="}[id.Ident]
		return value{"(" + codes[0] + " " + op + " " + codes[1] + ")", boolean}, nil
	case "not":
		if len(vals) != 1 {
			return value{}, errors.New("not: wrong number of arguments")
		}
		return value{"!" + truth(vals[0]), boolean}, nil
	}
	fn, ok := funcs[id.Ident]
	if !ok {
		return value{}, fmt.Errorf("%s: unknown function %q", f.loc(id), id.Ident)
	}
	return value{fn.code + "(" + strings.Join(codes, ", ") + ")", fn.res}, nil
}

func (f *funcGen) arg(n parse.Node, dot value) (value, error) {
	switch n := n.(type) {
	case *parse.DotNode:
		return dot, nil
	case *parse.FieldNode:
		return f.fields(dot, n.Ident)
	case *parse.VariableNode:
		v, err := f.lookupVar(n.Ident[0])
		if err != nil {
			return value{}, err
		}
		return f.fields(v, n.Ident[1:])
	case *parse.StringNode:
		return value{strconv.Quote(n.Text), types.Typ[types.String]}, nil
	case *parse.NumberNode:
		if !n.IsInt {
			return value{}, fmt.Errorf("%s: only integer numbers are supported", f.loc(n))
		}
		return value{n.Text, types.Typ[types.Int]}, nil
	case *parse.PipeNode:
		v, err := f.pipe(n, dot)
		if err != nil {
			return value{}, err
		}
		v.code = "(" + v.code + ")"
		return v, nil
	}
	return value{}, fmt.Errorf("%s: unsupported argument %q", f.loc(n), n)
}

// fields resolves a chain of field or method names on v.
func (f *funcGen) fields(v value, idents []string) (value, error) {
	for _, name := range idents {
		obj, _, _ := types.LookupFieldOrMethod(v.typ, true, f.g.pkg, name)
		switch obj := obj.(type) {
		case *types.Var:
			v = value{v.code + "." + name, obj.Type()}
		case *types.Func:
			sig := obj.Type().(*types.Signature)
			if sig.Params().Len() != 0 || sig.Results().Len() != 1 {
				return value{}, fmt.Errorf("method %s.%s: only methods without arguments returning a single value are supported", f.g.typeString(v.typ), name)
			}
			v = value{v.code + "." + name + "()", sig.Results().At(0).Type()}
		default:
			return value{}, fmt.Errorf("can't evaluate field %s in type %s", name, f.g.typeString(v.typ))
		}
	}
	return v, nil
}

// truth returns Go code evaluating whether v is true in the template sense.
func truth(v value) string {
	switch t := v.typ.Underlying().(type) {
	case *types.Basic:
		switch {
		case t.Info()&types.IsBoolean != 0:
			return v.code
		case t.Info()&types.IsString != 0:
			return "(" + v.code + " != \"\")"
		case t.Info()&types.IsNumeric != 0:
			return "(" + v.code + " != 0)"
		}
	case *types.Slice, *types.Map, *types.Chan:
		return "(len(" + v.code + ") != 0)"
	case *types.Array:
		return "(len(" + v.code + ") != 0)"
	case *types.Pointer, *types.Interface, *types.Signature:
		return "(" + v.code + " != nil)"
	case *types.Struct:
		return "true"
	}
	panic(fmt.Sprintf("truth: unsupported type %s", v.typ))
}
