name: publish docs

on:
  push:
    branches:
      - main
    tags:
      - v3.*

permissions:
  contents: read

jobs:
  test-docs:
    name: test-docs
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Set PATH
        run: echo "${GITHUB_WORKSPACE}/.local/bin" >>"${GITHUB_PATH}"

      - run: make ensure-gfmrun

      - run: make gfmrun
        env:
          FLAGS: --walk docs/v3/

      - run: make diffcheck

  publish:
    permissions:
      contents: write
    if: startswith(github.ref, 'refs/tags/')
    name: publish
    needs: [test-docs]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: pip
          cache-dependency-path: mkdocs-requirements.txt

      - name: Ensure mkdocs is available
        run: make ensure-mkdocs

      - name: Set mkdocs remote
        run: make set-mkdocs-remote
        env:
          MKDOCS_REMOTE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy via mkdocs
        run: make deploy-mkdocs
