.nh
.TH greet 8

.SH NAME
.PP
greet \- Some app


.SH SYNOPSIS
.PP
greet

.PP
.RS

.nf
[\-\-another\-flag|\-b]
[\-\-flag|\-\-fl|\-f]=[value]
[\-\-socket|\-s]=[value]

.fi
.RE


.SH DESCRIPTION
.PP
Description of the application.

.PP
\fBUsage\fP:

.PP
.RS

.nf
app [first\_arg] [second\_arg]

.fi
.RE


.SH GLOBAL OPTIONS
.PP
\fB\-\-another\-flag, \-b\fP: another usage text

.PP
\fB\-\-flag, \-\-fl, \-f\fP="":

.PP
\fB\-\-socket, \-s\fP="": some 'usage' text (default: value)


.SH COMMANDS
.SH config, c
.PP
another usage test

.PP
\fB\-\-another\-flag, \-b\fP: another usage text

.PP
\fB\-\-flag, \-\-fl, \-f\fP="":

.SS sub\-config, s, ss
.PP
another usage test

.PP
\fB\-\-sub\-command\-flag, \-s\fP: some usage text

.PP
\fB\-\-sub\-flag, \-\-sub\-fl, \-s\fP="":

.SH info, i, in
.PP
retrieve generic information

.SH some\-command
.SH usage, u
.PP
standard usage text

.PP
.RS

.nf
Usage for the usage text
\- formatted:  Based on the specified ConfigMap and summon secrets.yml
\- list:       Inspect the environment for a specific process running on a Pod
\- for\_effect: Compare 'namespace' environment with 'local'

```
func() { ... }
```

Should be a part of the same code block

.fi
.RE

.PP
\fB\-\-another\-flag, \-b\fP: another usage text

.PP
\fB\-\-flag, \-\-fl, \-f\fP="":

.SS sub\-usage, su
.PP
standard usage text

.PP
.RS

.PP
Single line of UsageText

.RE

.PP
\fB\-\-sub\-command\-flag, \-s\fP: some usage text
